### ISSUE TITLE
Error open plugin

### ISSUE THREAD

**Issue by sovaby** [Eviloid/plugin.video.evld.fanserials.tv#1]
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.evld.fanserials.tv/default.py", line 554, in <module>
                                                ABClist(params)
                                              File "/home/kodi/.kodi/addons/plugin.video.evld.fanserials.tv/default.py", line 163, in ABClist
                                                html = json.loads(get_html('%s/alphabet/%s/' % (BASE_URL, t)))['alphabet']
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2020-01-15 18:41:57.600 T:140694718629632   DEBUG: onExecutionDone(22, /home/kodi/.kodi/addons/plugin.video.evld.fanserials.tv/default.py)
2020-01-15 18:41:57.601 T:140698005620864   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-01-15 18:41:57.702 T:140694718629632    INFO: Python interpreter stopped
2020-01-15 18:41:57.702 T:140694718629632   DEBUG: Thread LanguageInvoker 140694718629632 terminating
2020-01-15 18:41:57.709 T:140696954599168   ERROR: GetDirectory - Error getting plugin://plugin.video.evld.fanserials.tv/?mode=abc&t=0
2020-01-15 18:41:57.709 T:140696954599168   DEBUG: Thread waiting 140696954599168 terminating
2020-01-15 18:41:57.717 T:140698005620864   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-01-15 18:41:57.718 T:140698005620864   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.evld.fanserials.tv/?mode=abc&t=0) failed
2020-01-15 18:41:57.718 T:140698005620864   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.evld.fanserials.tv/)
2020-01-15 18:41:57.718 T:140698005620864   DEBUG:   ParentPath = [plugin://]
2020-01-15 18:41:57.719 T:140698005620864   DEBUG: Loading items: 7, directory: plugin://plugin.video.evld.fanserials.tv/ sort method: 0, ascending: false
2020-01-15 18:41:57.731 T:140694727022336   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.evld.fanserials.tv] took 12 ms`

**Comment by Eviloid** [comment]
Подскажите какой хост используете (fanserials.**XX**) в настройках?
В браузере без впн и прочих уловок сайт доступен у Вас?

**Comment by Eviloid** [comment]
Попробуйте в настройках аддона поменять хост на fanserial.net или fanserials.network, надеюсь заработает с каким-нибудь из них (у меня оба работают).

**Comment by sovaby** [comment]
tv и net У меня не работет Ошибка как входишь в папку сериалы.

пт, 17 янв. 2020 г. в 11:53, Eviloid <notifications@github.com>:

**Comment by sovaby** [comment]
Во fanserials.network заработало именно fanserials не fanserial как вы
пишите .
Спасибо за плагин 👍

сб, 25 янв. 2020 г. в 16:38, Михаил Лукьянчиков <sovaby@gmail.com>:

**Comment by Eviloid** [comment]
У них разные зеркала для разных стран, да и меняются иногда. Рискну предположить, что Вы не из России и у Вас тоже есть "чудеса" с доступом к различным ресурсам ;)

Ну не важно, я рад что заработало и это главное. Приятного просмотра!
